server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_api
    username: psqluser
    password: psqluser

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: SECRET_KEY
  expiration: 86400000